import Head from "next/head";
import Navbar from "@/components/Navbar";
import { Table } from "@/components/Table";
import { useEffect, useState } from "react";
import { UserType } from "@/interface/UserType";
import { getUsers } from "@/lib/getUsers";

export default function Home() {
  const [users, setUsers] = useState<UserType[]>([]);

  const handleGetUsers = async () => {
    const users = await getUsers();
    setUsers(users);
  };

  useEffect(() => {
    handleGetUsers();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <Table users={users} />
      </main>
    </>
  );
}
