import Head from "next/head";
import Navbar from "@/components/Navbar";
import { Table } from "@/components/Table";
import axios from "axios";
import { useEffect, useState } from "react";

export interface UserType {
  id: number;
  firstName: string;
  lastName: string;
  userName: string;
  birthDate: string;
  email: string;
  phone: string;
  avatarURL: string;
}

export default function Home() {
  const [users, setUsers] = useState<UserType[]>([]);

  const getApi = () => {
    axios.get("https://dummyjson.com/users").then((response) => {
      const filteredUsers = response.data.users.map((user: any) => {
        return {
          id: user.id,
          firstName: user.firstName,
          lastName: user.lastName,
          userName: user.username,
          birthDate: user.birthDate,
          email: user.email,
          phone: user.phone,
          avatarURL: user.image,
        };
      });
      setUsers(filteredUsers);
    });
  };

  useEffect(() => {
    getApi();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <p className="text-3xl font-bold">users dummy</p>
        <Table users={users} />
      </main>
    </>
  );
}
